// frontend/src/components/ImageCard.vue
<template>
    <div class="container">
        <div class="card">
            <div class="imgBx">

            </div>
            <div class="content">

            </div>
        </div>
        <div class="card">
            <div class="imgBx">

            </div>
            <div class="content">

            </div>
        </div>
    </div>
</template>

<script setup>
</script>

<style scoped>
body {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  background: #333;
}

.container {
  position: relative;
  display: flex;
  align-items: center;

  .card {
    position: relative;
    width: 300px;
    height: 300px;
    background: #fff;
    border-radius: 40px;
    box-shadow: 0 20px 25px #00000040;
    transition: 0.5s;

    &:hover {
      height: 420px;
    }

    .imgBx {
      position: relative;
      width: 100%;
      height: 260px;
      background: #555;

      &::before {
        content: "";
        position: absolute;
        bottom: -40px;
        width: 100%;
        height: 80px;
        border-radius: 40px;
        background: #fff;
      }

      &::after {
        content: '';
        position: relative;
        right: 0;
        bottom: 40px;
        width: 80px;
        height: 80px;
        background: #0f0;
        border-radius: 50%;
        box-shadow: 75px 70px 0 40px #fff;
      }
    }

    .content {
      position: relative;
      top: -40px;
      z-index: 10;
      padding: 0 30px;
      transition: 0.5s;

      h3 {
        font-size: 1.25em;
      }
    }
  }
}
</style>

// frontend/src/components/ImageCard.jsx
import styled from 'styled-components'

const Container = styled.div`
  position: relative;
  display: flex;
  align-items: center;
`

const CardEl = styled.div`
  position: relative;
  width: 300px;
  height: 300px;
  background: #fff;
  border-radius: 40px;
  box-shadow: 0 20px 25px #00000040;
  transition: 0.5s;

  &:hover { height: 420px; }
`

const ImgBx = styled.div`
  position: relative;
  width: 100%;
  height: 260px;
  background: #555;

  &::before {
    content: "";
    position: absolute;
    bottom: -40px;
    width: 100%;
    height: 80px;
    border-radius: 40px;
    background: #fff;
  }

  &::after {
    content: '';
    position: relative;
    right: 0;
    bottom: 40px;
    width: 80px;
    height: 80px;
    background: #0f0;
    border-radius: 50%;
    box-shadow: 75px 70px 0 40px #fff;
  }
`

const Content = styled.div`
  position: relative;
  top: -40px;
  z-index: 10;
  padding: 0 30px;
  transition: 0.5s;
  h3 { font-size: 1.25em; }
`

export default function ImageCard() {
    return (
        <Container>
            <CardEl><ImgBx /><Content /></CardEl>
            <CardEl><ImgBx /><Content /></CardEl>
        </Container>
    )
}
