// frontend/src/components/Music.tsx
import { useState, useRef, useEffect, useCallback, useMemo } from 'react'
import styled, { keyframes } from 'styled-components'

function getMusicUrl(filename: string) {
    return new URL(`../assets/music/${filename}`, import.meta.url).href
}

const initialPlaylist = [
    {
        name: 'いつかこの恋を思い出してきっと泣いてしまう',
        artist_name: '得田真裕',
        audio: getMusicUrl('得田真裕 - いつかこの恋を思い出してきっと泣いてしまう.flac'),
    },
]

const STORAGE_KEY = 'music-widget-pos'

interface Position {
    x: number
    y: number
}

function loadPosition(): Position {
    try {
        const saved = localStorage.getItem(STORAGE_KEY)
        if (saved) return JSON.parse(saved)
    } catch { }
    return { x: 20, y: 20 }
}

const scrollText = keyframes`
  0%, 15% { transform: translateX(0); }
  85%, 100% { transform: translateX(calc(-100% + 180px)); }
`

const Widget = styled.div<{ $dragging: boolean }>`
  position: fixed;
  z-index: 9998;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 6px;
  padding: 10px 14px;
  border-radius: 16px;
  background: rgba(255, 255, 255, 0.08);
  backdrop-filter: blur(14px);
  -webkit-backdrop-filter: blur(14px);
  border: 1px solid rgba(255, 255, 255, 0.12);
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.18);
  user-select: none;
  cursor: ${(p) => (p.$dragging ? 'grabbing' : 'grab')};
  transition: box-shadow 0.3s ease;
  min-width: 140px;

  &:hover { box-shadow: 0 10px 40px rgba(0, 0, 0, 0.25); }
`

const Controls = styled.div`
  display: flex;
  align-items: center;
  gap: 6px;
`

const ControlBtn = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  height: clamp(2rem, 4vh, 2.8rem);
  width: clamp(2rem, 4vh, 2.8rem);
  border-radius: 50%;
  color: var(--frame-color);
  font-size: clamp(0.85rem, 1.6vh, 1.1rem);
  cursor: pointer;
  transition: transform 0.2s, color 0.2s;

  &:hover { transform: scale(1.15); color: var(--main-color); }
  &:active { transform: scale(0.95); }
`

const TrackInfo = styled.div`
  text-align: center;
  max-width: 180px;
  overflow: hidden;
`

const TrackText = styled.span`
  font-family: var(--content-font);
  font-size: clamp(0.6rem, 1vh, 0.75rem);
  color: var(--frame-color);
  opacity: 0.75;
  white-space: nowrap;
  display: inline-block;
  animation: ${scrollText} 12s linear infinite;
`

const ToggleBtn = styled.div`
  cursor: pointer;
  color: var(--frame-color);
  opacity: 0.4;
  font-size: 0.6rem;
  transition: opacity 0.2s;
  padding: 0 4px;
  &:hover { opacity: 0.8; }
`

export default function Music() {
    const [playlist] = useState(initialPlaylist)
    const [currentIndex, setCurrentIndex] = useState(0)
    const [isPlaying, setIsPlaying] = useState(false)
    const [loading] = useState(false)
    const [expanded, setExpanded] = useState(false)
    const [position, setPosition] = useState<Position>(loadPosition)
    const [isDragging, setIsDragging] = useState(false)

    const audioRef = useRef<HTMLAudioElement>(null)
    const widgetRef = useRef<HTMLDivElement>(null)
    const dragOffset = useRef({ x: 0, y: 0 })

    const currentTrack = useMemo(() => playlist[currentIndex] || null, [playlist, currentIndex])

    const savePosition = useCallback((pos: Position) => {
        try { localStorage.setItem(STORAGE_KEY, JSON.stringify(pos)) } catch { }
    }, [])

    const startDrag = useCallback((e: React.MouseEvent | React.TouchEvent) => {
        const target = e.target as HTMLElement
        if (target.closest('[data-control]') || target.closest('[data-toggle]')) return
        setIsDragging(true)
        const clientX = 'touches' in e ? e.touches[0].clientX : (e as React.MouseEvent).clientX
        const clientY = 'touches' in e ? e.touches[0].clientY : (e as React.MouseEvent).clientY
        setPosition((prev) => {
            dragOffset.current = { x: clientX - prev.x, y: clientY - prev.y }
            return prev
        })
    }, [])

    useEffect(() => {
        if (!isDragging) return
        const onDrag = (e: MouseEvent | TouchEvent) => {
            e.preventDefault()
            const clientX = 'touches' in e ? e.touches[0].clientX : (e as MouseEvent).clientX
            const clientY = 'touches' in e ? e.touches[0].clientY : (e as MouseEvent).clientY
            const el = widgetRef.current
            if (!el) return
            const maxX = window.innerWidth - el.offsetWidth
            const maxY = window.innerHeight - el.offsetHeight
            setPosition({
                x: Math.max(0, Math.min(clientX - dragOffset.current.x, maxX)),
                y: Math.max(0, Math.min(clientY - dragOffset.current.y, maxY)),
            })
        }
        const stopDrag = () => {
            setIsDragging(false)
            setPosition((pos) => { savePosition(pos); return pos })
        }
        document.addEventListener('mousemove', onDrag)
        document.addEventListener('mouseup', stopDrag)
        document.addEventListener('touchmove', onDrag, { passive: false })
        document.addEventListener('touchend', stopDrag)
        return () => {
            document.removeEventListener('mousemove', onDrag)
            document.removeEventListener('mouseup', stopDrag)
            document.removeEventListener('touchmove', onDrag)
            document.removeEventListener('touchend', stopDrag)
        }
    }, [isDragging, savePosition])

    useEffect(() => {
        const clamp = () => {
            const el = widgetRef.current
            if (!el) return
            const maxX = window.innerWidth - el.offsetWidth
            const maxY = window.innerHeight - el.offsetHeight
            setPosition((prev) => {
                const clamped = {
                    x: Math.max(0, Math.min(prev.x, maxX)),
                    y: Math.max(0, Math.min(prev.y, maxY)),
                }
                savePosition(clamped)
                return clamped
            })
        }
        window.addEventListener('resize', clamp)
        requestAnimationFrame(clamp)
        return () => window.removeEventListener('resize', clamp)
    }, [savePosition])

    const togglePlay = () => {
        if (!audioRef.current || !currentTrack) return
        if (isPlaying) { audioRef.current.pause() } else { audioRef.current.play().catch(() => { }) }
        setIsPlaying(!isPlaying)
    }

    const prevTrack = () => {
        if (playlist.length === 0) return
        setCurrentIndex(currentIndex === 0 ? playlist.length - 1 : currentIndex - 1)
    }

    const nextTrack = useCallback(() => {
        if (playlist.length === 0) return
        setCurrentIndex((prev) => (prev + 1) % playlist.length)
    }, [playlist.length])

    useEffect(() => {
        if (!audioRef.current) return
        audioRef.current.load()
        if (isPlaying) audioRef.current.play().catch(() => { })
    }, [currentIndex]) // eslint-disable-line react-hooks/exhaustive-deps

    return (
        <Widget
            $dragging={isDragging}
            style={{ left: `${position.x}px`, top: `${position.y}px` }}
            ref={widgetRef}
            onMouseDown={startDrag}
            onTouchStart={startDrag}
        >
            <Controls>
                <ControlBtn data-control="" data-glass-hover="" onClick={prevTrack}>
                    <i className="fas fa-step-backward"></i>
                </ControlBtn>
                <ControlBtn data-control="" data-glass-hover="" onClick={togglePlay}>
                    <i className={`fas ${loading ? 'fa-spinner fa-spin' : isPlaying ? 'fa-pause' : 'fa-play'}`}></i>
                </ControlBtn>
                <ControlBtn data-control="" data-glass-hover="" onClick={nextTrack}>
                    <i className="fas fa-step-forward"></i>
                </ControlBtn>
            </Controls>

            {expanded && (
                <TrackInfo>
                    <TrackText>
                        {currentTrack ? `${currentTrack.name} - ${currentTrack.artist_name}` : loading ? 'Loading...' : 'No track'}
                    </TrackText>
                </TrackInfo>
            )}

            <ToggleBtn data-toggle="" onClick={() => setExpanded(!expanded)}>
                <i className={`fas ${expanded ? 'fa-chevron-up' : 'fa-chevron-down'}`}></i>
            </ToggleBtn>

            <audio ref={audioRef} src={currentTrack?.audio} onEnded={nextTrack} onError={() => setIsPlaying(false)} preload="auto" />
        </Widget>
    )
}

// frontend/src/components/Music.vue
<template>
<div 
    class="music-widget"
    :style="widgetStyle"
    ref="widgetRef"
>
    <!-- Drag Handle -->
    <div 
        class="drag-handle"
        @mousedown="startDrag"
        @touchstart.prevent="startDrag"
    >
        <i class="fas fa-grip-lines"></i>
    </div>

    <!-- Player Controls -->
    <div class="player-controls">
        <div class="control-btn" data-glass-hover @click="prevTrack" :disabled="loading">
            <i class="fas fa-step-backward"></i>
        </div>
        <div class="control-btn" data-glass-hover @click="togglePlay" :disabled="loading">
            <i :class="['fas', loading ? 'fa-spinner fa-spin' : (isPlaying ? 'fa-pause' : 'fa-play')]"></i>
        </div>
        <div class="control-btn" data-glass-hover @click="nextTrack" :disabled="loading">
            <i class="fas fa-step-forward"></i>
        </div>
    </div>

    <!-- Track Info (collapsible) -->
    <div class="track-info" v-if="expanded">
        <span class="track-text" v-if="currentTrack">{{ currentTrack.name }} - {{ currentTrack.artist_name }}</span>
        <span class="track-text" v-else>{{ loading ? 'Loading...' : 'No track' }}</span>
    </div>

    <!-- Toggle expand/collapse -->
    <div class="toggle-btn" @click="expanded = !expanded">
        <i :class="['fas', expanded ? 'fa-chevron-up' : 'fa-chevron-down']"></i>
    </div>

    <audio 
        ref="audioRef" 
        :src="currentTrack?.audio"
        @ended="nextTrack"
        @canplay="onCanPlay"
        @error="handleAudioError"
        preload="auto"
    ></audio>
</div>
</template>

<script setup>
import { ref, computed, onMounted, onBeforeUnmount } from 'vue'

// ─── Music URL Helper ───
function getMusicUrl(filename) {
    return new URL(`../assets/music/${filename}`, import.meta.url).href
}

// ─── Playlist ───
const playlist = ref([
    { 
        name: 'いつかこの恋を思い出してきっと泣いてしまう', 
        artist_name: '得田真裕',
        audio: getMusicUrl('得田真裕 - いつかこの恋を思い出してきっと泣いてしまう.flac')
    }
])

// ─── Player State ───
const currentIndex = ref(0)
const isPlaying = ref(false)
const loading = ref(false)
const audioRef = ref(null)
const expanded = ref(false)

const currentTrack = computed(() => playlist.value[currentIndex.value] || null)

// ─── Drag State ───
const widgetRef = ref(null)
const STORAGE_KEY = 'music-widget-pos'

const position = ref(loadPosition())

function loadPosition() {
    try {
        const saved = localStorage.getItem(STORAGE_KEY)
        if (saved) return JSON.parse(saved)
    } catch {}
    return { x: 20, y: 20 }
}

function savePosition() {
    try {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(position.value))
    } catch {}
}

const widgetStyle = computed(() => ({
    left: `${position.value.x}px`,
    top: `${position.value.y}px`,
}))

let isDragging = false
let dragOffset = { x: 0, y: 0 }

function startDrag(e) {
    isDragging = true
    const clientX = e.touches ? e.touches[0].clientX : e.clientX
    const clientY = e.touches ? e.touches[0].clientY : e.clientY
    dragOffset.x = clientX - position.value.x
    dragOffset.y = clientY - position.value.y

    document.addEventListener('mousemove', onDrag)
    document.addEventListener('mouseup', stopDrag)
    document.addEventListener('touchmove', onDrag, { passive: false })
    document.addEventListener('touchend', stopDrag)
}

function onDrag(e) {
    if (!isDragging) return
    e.preventDefault()
    const clientX = e.touches ? e.touches[0].clientX : e.clientX
    const clientY = e.touches ? e.touches[0].clientY : e.clientY

    const el = widgetRef.value
    if (!el) return

    const maxX = window.innerWidth - el.offsetWidth
    const maxY = window.innerHeight - el.offsetHeight

    position.value = {
        x: Math.max(0, Math.min(clientX - dragOffset.x, maxX)),
        y: Math.max(0, Math.min(clientY - dragOffset.y, maxY)),
    }
}

function stopDrag() {
    isDragging = false
    savePosition()
    document.removeEventListener('mousemove', onDrag)
    document.removeEventListener('mouseup', stopDrag)
    document.removeEventListener('touchmove', onDrag)
    document.removeEventListener('touchend', stopDrag)
}

// ─── Keep widget in bounds on resize ───
function clampPosition() {
    const el = widgetRef.value
    if (!el) return
    const maxX = window.innerWidth - el.offsetWidth
    const maxY = window.innerHeight - el.offsetHeight
    position.value = {
        x: Math.max(0, Math.min(position.value.x, maxX)),
        y: Math.max(0, Math.min(position.value.y, maxY)),
    }
    savePosition()
}

onMounted(() => {
    window.addEventListener('resize', clampPosition)
    // initial clamp
    requestAnimationFrame(clampPosition)
})

onBeforeUnmount(() => {
    window.removeEventListener('resize', clampPosition)
})

// ─── Player Controls ───
function togglePlay() {
    if (!audioRef.value || !currentTrack.value) return
    if (isPlaying.value) {
        audioRef.value.pause()
    } else {
        audioRef.value.play().catch(() => {})
    }
    isPlaying.value = !isPlaying.value
}

function prevTrack() {
    if (playlist.value.length === 0) return
    currentIndex.value = currentIndex.value === 0 ? playlist.value.length - 1 : currentIndex.value - 1
    playNewTrack()
}

function nextTrack() {
    if (playlist.value.length === 0) return
    currentIndex.value = (currentIndex.value + 1) % playlist.value.length
    playNewTrack()
}

function playNewTrack() {
    if (!audioRef.value) return
    audioRef.value.load()
    if (isPlaying.value) {
        audioRef.value.play().catch(() => {})
    }
}

function onCanPlay() {
    console.log('Audio ready to play:', currentTrack.value?.name)
}

function handleAudioError(e) {
    console.error('Audio playback error:', e.target?.error?.message || 'Unknown error')
    isPlaying.value = false
}
</script>

<style scoped>
.music-widget {
  position: fixed;
  z-index: 9998;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 6px;
  padding: 10px 14px;
  border-radius: 16px;
  background: rgba(255, 255, 255, 0.08);
  backdrop-filter: blur(14px);
  -webkit-backdrop-filter: blur(14px);
  border: 1px solid rgba(255, 255, 255, 0.12);
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.18);
  user-select: none;
  transition: box-shadow 0.3s ease;
  min-width: 140px;

  &:hover {
    box-shadow: 0 10px 40px rgba(0, 0, 0, 0.25);
  }
}

.drag-handle {
  width: 100%;
  display: flex;
  justify-content: center;
  cursor: grab;
  padding: 2px 0;
  color: var(--frame-color);
  opacity: 0.4;
  font-size: 0.75rem;
  transition: opacity 0.2s;

  &:active {
    cursor: grabbing;
  }

  &:hover {
    opacity: 0.8;
  }
}

.player-controls {
  display: flex;
  align-items: center;
  gap: 6px;

  .control-btn {
    display: flex;
    justify-content: center;
    align-items: center;
    height: clamp(2rem, 4vh, 2.8rem);
    width: clamp(2rem, 4vh, 2.8rem);
    border-radius: 50%;
    color: var(--frame-color);
    font-size: clamp(0.85rem, 1.6vh, 1.1rem);
    cursor: pointer;
    transition: transform 0.2s, color 0.2s;

    &:hover {
      transform: scale(1.15);
      color: var(--main-color);
    }

    &:active {
      transform: scale(0.95);
    }
  }
}

.track-info {
  text-align: center;
  max-width: 180px;
  overflow: hidden;
}

.track-text {
  font-family: var(--content-font);
  font-size: clamp(0.6rem, 1vh, 0.75rem);
  color: var(--frame-color);
  opacity: 0.75;
  white-space: nowrap;
  display: inline-block;
  animation: scroll-text 12s linear infinite;
}

@keyframes scroll-text {
  0%, 15% { transform: translateX(0); }
  85%, 100% { transform: translateX(calc(-100% + 180px)); }
}

.toggle-btn {
  cursor: pointer;
  color: var(--frame-color);
  opacity: 0.4;
  font-size: 0.6rem;
  transition: opacity 0.2s;
  padding: 0 4px;

  &:hover {
    opacity: 0.8;
  }
}
</style>
