// frontend/src/components/Quote.vue
<template>
    <div class="random-quote-box" >
        <div class="quote-icon">
            <i class="fas fa-quote-left"></i>
        </div>
        <div class="quote-content">
            {{ displayText }}
        </div>
        <div class="quote-icon">
            <i class="fas fa-quote-right"></i>
        </div>
    </div>
</template>
<script setup>
import { ref, watch, onMounted, onUnmounted } from 'vue'
import { useLocaleStore } from '../stores/locale'
import { fetchRandomQuote } from '../api/quotes'

const localeStore = useLocaleStore()

const currentQuote = ref('')
const displayText = ref('')
const quoteLoading = ref(false)
const isTyping = ref(false)

let animationTimer = null
let autoRefreshTimer = null

// 自动刷新间隔（毫秒）
const AUTO_REFRESH_INTERVAL = 10000

/* 清除动画定时器 */
function clearAnimation() {
  if (animationTimer) {
    clearTimeout(animationTimer)
    animationTimer = null
  }
}

/* 清除自动刷新定时器 */
function clearAutoRefresh() {
  if (autoRefreshTimer) {
    clearTimeout(autoRefreshTimer)
    autoRefreshTimer = null
  }
}

/* 开始自动刷新计时 */
function scheduleAutoRefresh() {
  clearAutoRefresh()
  autoRefreshTimer = setTimeout(() => {
    refreshQuote()
  }, AUTO_REFRESH_INTERVAL)
}

/* 打字动画 */
function startTyping(text, onComplete) {
  let index = 0

  const type = () => {
    if (index < text.length) {
      displayText.value += text[index]
      index++
      animationTimer = setTimeout(type, 80)
    } else {
      isTyping.value = false
      onComplete?.()
    }
  }

  type()
}

/* 删除动画 */
function startDeleting(onComplete) {
  const deleteChar = () => {
    if (displayText.value.length > 0) {
      displayText.value = displayText.value.slice(0, -1)
      animationTimer = setTimeout(deleteChar, 40)
    } else {
      onComplete?.()
    }
  }

  deleteChar()
}

/* 先删除旧文字，再打字显示新文字 */
function animateQuoteChange(newQuote) {
  clearAnimation()
  isTyping.value = true

  // 如果当前有文字，先删除
  if (displayText.value.length > 0) {
    startDeleting(() => {
      startTyping(newQuote, scheduleAutoRefresh)
    })
  } else {
    // 直接打字
    startTyping(newQuote, scheduleAutoRefresh)
  }
}

/* 拉取名言 */
async function refreshQuote() {
  if (quoteLoading.value) return

  clearAutoRefresh()
  quoteLoading.value = true
  try {
    const quote = await fetchRandomQuote(localeStore.locale)
    currentQuote.value = quote
    animateQuoteChange(quote)
  } catch (error) {
    console.error('Failed to fetch random quote:', error)
    const errorText =
      localeStore.locale === 'zh-CN'
        ? '获取名言失败，请稍后重试'
        : 'Failed to load quote, please try again'

    currentQuote.value = errorText
    animateQuoteChange(errorText)
  } finally {
    quoteLoading.value = false
  }
}

/* 语言切换自动刷新 */
watch(() => localeStore.locale, () => {
  refreshQuote()
})

onMounted(() => {
  refreshQuote()
})

onUnmounted(() => {
  clearAnimation()
  clearAutoRefresh()
})
</script>


<style scoped>
.random-quote-box {
  text-align: center;
  color: var(--frame-color);
  max-width: 600px;
  border-radius: 5px;
  padding: 10px;
  backdrop-filter: blur(1px);
  -webkit-backdrop-filter: blur(1px);
  background-color: var(--glass-bg-color);
  box-shadow: 0 4px 30px #00000030;
}

.quote-icon {
  font-size: clamp(1rem, 2.5vh, 2rem);
}

.quote-content {
  font-family: var(--content-font);
  font-size: clamp(1rem, 1.5vh + 0.5rem, 1.4rem);
  margin: clamp(0.5rem, 1.5vh, 1.5rem) 0;

  &::after {
    content: '|';
    margin-left: 2px;
    animation: blink 1s infinite;
  }
}

@keyframes blink {
  50% { opacity: 0; }
}

@media (max-width: 768px) {
  .random-quote-box {
    margin: 0 20px 0 20px;
  }
}
</style>

// frontend/src/components/Quote.tsx
import { useState, useEffect, useRef, useCallback } from 'react'
import styled, { keyframes } from 'styled-components'
import { useLocale } from '../stores/LocaleContext'
import { fetchRandomQuote } from '../api/quotes'

const AUTO_REFRESH_INTERVAL = 10000

const blink = keyframes`
  50% { opacity: 0; }
`

const QuoteBox = styled.div`
  text-align: center;
  color: var(--frame-color);
  max-width: 600px;
  border-radius: 5px;
  padding: 10px;
  backdrop-filter: blur(1px);
  -webkit-backdrop-filter: blur(1px);
  background-color: var(--glass-bg-color);
  box-shadow: 0 4px 30px #00000030;

  @media (max-width: 768px) { margin: 0 20px; }
`

const QuoteIcon = styled.div`
  font-size: clamp(1rem, 2.5vh, 2rem);
`

const QuoteContent = styled.div`
  font-family: var(--content-font);
  font-size: clamp(1rem, 1.5vh + 0.5rem, 1.4rem);
  margin: clamp(0.5rem, 1.5vh, 1.5rem) 0;

  &::after {
    content: '|';
    margin-left: 2px;
    animation: ${blink} 1s infinite;
  }
`

export default function Quote() {
    const { locale } = useLocale()
    const [displayText, setDisplayText] = useState('')
    const [quoteLoading, setQuoteLoading] = useState(false)
    const animationTimerRef = useRef<NodeJS.Timeout | null>(null)
    const autoRefreshTimerRef = useRef<NodeJS.Timeout | null>(null)
    const localeRef = useRef(locale)

    useEffect(() => { localeRef.current = locale }, [locale])

    const clearAnimation = useCallback(() => {
        if (animationTimerRef.current) { clearTimeout(animationTimerRef.current); animationTimerRef.current = null }
    }, [])

    const clearAutoRefresh = useCallback(() => {
        if (autoRefreshTimerRef.current) { clearTimeout(autoRefreshTimerRef.current); autoRefreshTimerRef.current = null }
    }, [])

    const refreshQuoteRef = useRef<(() => Promise<void>) | null>(null)

    const scheduleAutoRefresh = useCallback(() => {
        clearAutoRefresh()
        autoRefreshTimerRef.current = setTimeout(() => refreshQuoteRef.current?.(), AUTO_REFRESH_INTERVAL)
    }, [clearAutoRefresh])

    const startTyping = useCallback((text: string, onComplete?: () => void) => {
        let index = 0
        const type = () => {
            if (index < text.length) {
                const char = text[index]; index++
                setDisplayText((prev) => prev + char)
                animationTimerRef.current = setTimeout(type, 80)
            } else { onComplete?.() }
        }
        type()
    }, [])

    const startDeleting = useCallback((currentText: string, onComplete?: () => void) => {
        let remaining = currentText
        const deleteChar = () => {
            if (remaining.length > 0) {
                remaining = remaining.slice(0, -1)
                setDisplayText(remaining)
                animationTimerRef.current = setTimeout(deleteChar, 40)
            } else { onComplete?.() }
        }
        deleteChar()
    }, [])

    const animateQuoteChange = useCallback((newQuote: string, currentDisplayText: string) => {
        clearAnimation()
        if (currentDisplayText.length > 0) {
            startDeleting(currentDisplayText, () => startTyping(newQuote, scheduleAutoRefresh))
        } else {
            startTyping(newQuote, scheduleAutoRefresh)
        }
    }, [clearAnimation, startDeleting, startTyping, scheduleAutoRefresh])

    const refreshQuote = useCallback(async () => {
        if (quoteLoading) return
        clearAutoRefresh()
        setQuoteLoading(true)
        try {
            const quote = await fetchRandomQuote(localeRef.current)
            setDisplayText((prev) => { animateQuoteChange(quote, prev); return prev })
        } catch (error) {
            console.error('Failed to fetch random quote:', error)
            const errorText = localeRef.current === 'zh-CN' ? '获取名言失败，请稍后重试' : 'Failed to load quote, please try again'
            setDisplayText((prev) => { animateQuoteChange(errorText, prev); return prev })
        } finally {
            setQuoteLoading(false)
        }
    }, [quoteLoading, clearAutoRefresh, animateQuoteChange])

    useEffect(() => { refreshQuoteRef.current = refreshQuote }, [refreshQuote])

    useEffect(() => {
        refreshQuoteRef.current?.()
        return () => { clearAnimation(); clearAutoRefresh() }
    }, []) // eslint-disable-line react-hooks/exhaustive-deps

    const prevLocaleRef = useRef(locale)
    useEffect(() => {
        if (prevLocaleRef.current !== locale) { prevLocaleRef.current = locale; refreshQuoteRef.current?.() }
    }, [locale])

    return (
        <QuoteBox>
            <QuoteIcon><i className="fas fa-quote-left"></i></QuoteIcon>
            <QuoteContent>{displayText}</QuoteContent>
            <QuoteIcon><i className="fas fa-quote-right"></i></QuoteIcon>
        </QuoteBox>
    )
}
